### ISSUE TITLE
L or other distance modules are not recognized

### ISSUE THREAD

**Issue by BMP-TUD** [pysal/pointpats#65]
Hello, 

Thank you very much for creating this package, it is amazing, but I have encountered a problem with it. I imported it as said in the documentation, I checked the requirements, all packages are satisfying them, and I am working with Python 3.7.7.. But still while calling pointpats.L(pp) Python says that there is no attribute L. Have someone encountered this problem? I have attached my import section and the code (not very long). Thank you for your help.

Greetings 
Bartosz

`import scipy.spatial
import pointpats
import libpysal as ps` 

`pp=pointpats.PointPattern(points)
 L_Test=pointpats.L(pp)`

Result:

`L_Test=pointpats.L(pp) :

AttributeError: module 'pointpats' has no attribute 'L'`

**Comment by ljwolf** [comment]
The distance-based statistics are now located at `pointpats.distance_statistics`. You may want to `from pointpats import distance_statistics as stats` and then use `stats.L()` or [the new `stats.l_test()`](https://github.com/pysal/pointpats/blob/master/notebooks/distance_statistics-numpy-oriented.ipynb), which should be documented in our [geographicdata.science/book](geographicdata.science/book) very soon 😄
